version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=integracao_hubspot
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=default
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: app
    build:
      context: ../
      dockerfile: infra/app/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/integracao_hubspot
    ports:
      - "8090:8090"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok:latest
    command: http app:8090 --log=stdout
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    depends_on:
      - app
    networks:
      - app-network

  public-url-registry:
    container_name: public-url-registry
    build:
      context: ./public-url-registry
      dockerfile: Dockerfile
    depends_on:
        - ngrok
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
